services:
  database:
    image: influxdb:2.6.1
    ports:
      - "8086:8086"
    env_file:
      - influxdb_credentials.env
    volumes:
      - ./database/init_scripts:/docker-entrypoint-initdb.d

  simulator:
    build: simulator/.
    ports: 
      - "5005:5005/udp"
    env_file:
      - influxdb_credentials.env

  reciever:
    build: reciever/.
    ports:
      - "5004:5004/udp"
    env_file:
      - influxdb_credentials.env

  forecasting_gpu:
    build:
      context: forecasting/
      dockerfile: gpu/Dockerfile
    env_file:
      - influxdb_credentials.env
    volumes:
      - ./forecasting/model:/forecasting/model
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    profiles: ["gpu"]
  
  forecasting_cpu:
    build:
      context: forecasting/
      dockerfile: cpu/Dockerfile
    env_file:
      - influxdb_credentials.env
    volumes:
      - ./forecasting/model:/forecasting/model
    profiles: ["cpu"]
