services:
  database:
    image: influxdb:2.6.1
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=prueba
      - DOCKER_INFLUXDB_INIT_PASSWORD=Prueba1234
      - DOCKER_INFLUXDB_INIT_ORG=TFG
      - DOCKER_INFLUXDB_INIT_BUCKET=AGV
      - DOCKER_INFLUXDB_INIT_MODE=setup

  simulator:
    build: simulator/.
    ports: 
      - "5005:5005/udp"

  reciever:
    build: reciever/.
    ports:
      - "5004:5004/udp"
