services:
  database:
    image: influxdb:2.6.1
    ports:
      - "8086:8086"
    env_file:
      - influxdb_credentials.env

  simulator:
    build: simulator/.
    ports: 
      - "5005:5005/udp"
    env_file:
      - influxdb_credentials.env

  reciever:
    build: reciever/.
    ports:
      - "5004:5004/udp"
    env_file:
      - influxdb_credentials.env

  forecasting:
    build: forecasting/.
    env_file:
      - influxdb_credentials.env
