name: pylint score

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint certifi==2022.12.7 influxdb-client==1.36.1 python-dateutil==2.8.2 reactivex==4.0.4 six==1.16.0 startrek==0.4.1 typing_extensions==4.5.0 udp==0.5.10 urllib3==1.26.14 darts==0.24
      - name: Run linting
        run: |
          pylint --fail-under=7.0 --recursive=y -f text services > linting.txt
      - name: Archive linting report
        uses: actions/upload-artifact@v3
        with:
          name: linting-report
          path: |
            linting.txt